2020-10-19 20:45:48,952 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:22:16,478 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:23:29,523 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:24:42,323 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:24:54,254 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:31:40,065 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:31:40,811 ERROR: Exception on /subject/1 [GET] [in c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask_login\utils.py", line 270, in decorated_view
    elif not current_user.is_authenticated:
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask_login\utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask_login\utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask_login\login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "C:\Users\ponei\github\CrowdQuiz\app\models.py", line 12, in load_user
    return User.query.get(int(id))
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\sqlalchemy\orm\base.py", line 451, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\sqlalchemy\orm\base.py", line 430, in _inspect_mapped_class
    mapper._configure_all()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1352, in _configure_all
    configure_mappers()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3299, in configure_mappers
    mapper._post_configure_properties()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1965, in _post_configure_properties
    prop.init()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 197, in init
    self.do_init()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2080, in do_init
    self._generate_backref()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2333, in _generate_backref
    % (backref_key, self, m)
sqlalchemy.exc.ArgumentError: Error creating backref 'questions' on relationship 'Topic.topics': property of that name exists on mapper 'mapped class QuestionTopics->question_topics'
2020-10-21 14:32:18,535 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:33:51,803 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:34:17,041 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:34:37,432 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
2020-10-21 14:35:46,656 INFO: CrowdQuiz startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:56]
