2020-10-17 23:35:13,951 ERROR: Exception on /delete_question/15/ [POST] [in c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\ponei\github\CrowdQuiz\app\routes.py", line 203, in delete_question
    if submit:
NameError: name 'submit' is not defined
2020-10-17 23:35:31,778 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:36:19,735 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:40:13,537 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:40:59,365 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:41:32,704 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:42:37,026 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:44:45,803 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:47:32,384 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:51:40,512 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:52:04,647 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:56:48,605 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:57:29,202 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:58:28,764 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-17 23:58:49,044 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-18 00:02:04,622 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-18 00:13:03,262 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
2020-10-18 00:13:07,085 ERROR: Exception on /user/susie [GET] [in c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\ponei\github\CrowdQuiz\app\routes.py", line 23, in user
    questions = Question.query.filter_by(user_id=user.id).order_by(desc(Question.id)).limit(20)
NameError: name 'desc' is not defined
2020-10-18 00:13:37,432 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:50]
